spring:
  application:
    name: demo
  datasource:
    url: jdbc:postgresql://localhost:5432/assig1
    username: postgres
    password: postgres
  sql:
    init:
      platform: postgres
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
    show-sql: true
server:
  port: 8080
jwt:
  secret: ${JWT_SECRET}
  expiration: 86400000
